//
// Created by Whisky on 1/14/2024.
//

#ifndef HELLOWORLD_JUMPTOBOOTLOADER_H
#define HELLOWORLD_JUMPTOBOOTLOADER_H

#ifndef SYSTEM_BOOTLOADER_ADDR
    #define SYSTEM_BOOTLOADER_ADDR (0x1FF09800U)
#endif

void JumpToBootloader(void);

#endif //HELLOWORLD_JUMPTOBOOTLOADER_H
